apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: music

resources:
  - 10-storage.yaml
  - 20-navidrome.yaml
  - 30-importer.yaml
  - 40-explo.yaml

commonLabels:
  app.kubernetes.io/part-of: navidrome
